name: Continuos Integration end Delivery with Github Actions

on:
  push:
    branches: 
      - "main"
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: 'jcfalves'
        password: 'dckr_pat_jCNhsWuSdWJPOhiUdgnh7mm5R30'
    
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Build Application .jar
      working-directory: ./spring341_docker_git_actions_/rest-with-spring-boot-and-java-erudio
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: .
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag 'jcfalves'/rest-with-spring-boot-erudio:latest 'jcfalves'/rest-with-spring-boot-erudio:${{ github.run_id }}
        
        docker push 'jcfalves'/rest-with-spring-boot-erudio:latest
        docker push 'jcfalves'/rest-with-spring-boot-erudio:${{ github.run_id }}

        
